/**
 * Versioned PvP typing lexicon.
 *
 * Curated snapshot from sinhvienaiti/typing-game shared vocabulary lookup,
 * levels 001-020. Duel authority uses this local snapshot so prompt selection
 * stays deterministic and does not depend on browser fetches.
 */
export const DUEL_LEXICON_VERSION = "duel-lexicon-v1";

export type DuelLexiconEntry = {
  wordId: string;
  token: string;
  length: number;
  difficultyClass: "core";
  topicTags: readonly string[];
  sourceLevel: number;
};

const WORDS_BY_LENGTH = Object.freeze({
  4: [
    ["good",1],
    ["cold",1],
    ["easy",1],
    ["hard",1],
    ["time",1],
    ["year",1],
    ["week",1],
    ["home",1],
    ["room",1],
    ["work",1],
    ["name",1],
    ["book",1],
    ["word",1],
    ["idea",1],
    ["food",1],
    ["city",1],
    ["road",1],
    ["game",1],
    ["care",1],
    ["kind",1],
    ["news",1],
    ["team",1],
    ["come",1],
    ["make",1],
    ["take",1],
    ["give",1],
    ["look",1],
    ["know",1],
    ["want",1],
    ["need",1],
    ["like",1],
    ["love",1],
    ["help",1],
    ["find",1],
    ["read",1],
    ["play",1],
    ["stop",1],
    ["open",1],
    ["live",1],
    ["feel",1],
    ["tell",1],
    ["just",1],
    ["also",1],
    ["only",1],
    ["then",1],
    ["very",1],
    ["here",1],
    ["life",1],
    ["away",1],
    ["real",1],
    ["case",1],
    ["mean",1],
    ["once",1],
    ["side",1],
    ["line",1],
    ["talk",1],
    ["girl",1],
    ["nice",1],
    ["soon",1],
    ["fire",1],
    ["list",1],
    ["baby",1],
    ["town",1],
    ["hear",1],
    ["wife",1],
    ["date",1],
    ["late",2],
    ["sure",2],
    ["free",2],
    ["full",2],
    ["weak",2],
    ["fast",2],
  ],
  5: [
    ["small",1],
    ["young",1],
    ["happy",1],
    ["right",1],
    ["wrong",1],
    ["night",1],
    ["today",1],
    ["house",1],
    ["woman",1],
    ["child",1],
    ["water",1],
    ["money",1],
    ["place",1],
    ["phone",1],
    ["music",1],
    ["story",1],
    ["group",1],
    ["think",1],
    ["write",1],
    ["speak",1],
    ["learn",1],
    ["start",1],
    ["close",1],
    ["drink",1],
    ["about",1],
    ["there",1],
    ["first",1],
    ["great",1],
    ["thing",1],
    ["point",1],
    ["later",1],
    ["thank",1],
    ["field",1],
    ["early",2],
    ["never",2],
    ["often",2],
    ["again",2],
    ["maybe",2],
    ["empty",2],
    ["clean",2],
    ["dirty",2],
    ["short",2],
    ["ready",2],
    ["clear",2],
    ["watch",2],
    ["sleep",2],
    ["drive",2],
    ["stand",2],
    ["bring",2],
    ["leave",2],
    ["build",2],
    ["check",2],
    ["study",2],
    ["teach",2],
    ["visit",2],
    ["order",2],
    ["price",2],
    ["world",2],
    ["video",2],
    ["level",2],
    ["after",2],
    ["still",2],
    ["state",2],
    ["power",2],
    ["whole",2],
    ["court",2],
    ["death",2],
    ["human",2],
    ["third",2],
    ["quite",2],
    ["space",2],
    ["heart",3],
  ],
  6: [
    ["please",1],
    ["thanks",1],
    ["school",1],
    ["family",1],
    ["friend",1],
    ["people",1],
    ["person",1],
    ["mother",1],
    ["father",1],
    ["sister",1],
    ["answer",1],
    ["health",1],
    ["listen",1],
    ["before",1],
    ["better",1],
    ["little",1],
    ["future",1],
    ["summer",1],
    ["always",2],
    ["really",2],
    ["simple",2],
    ["enough",2],
    ["strong",2],
    ["change",2],
    ["choose",2],
    ["decide",2],
    ["forget",2],
    ["follow",2],
    ["happen",2],
    ["return",2],
    ["create",2],
    ["travel",2],
    ["number",2],
    ["result",2],
    ["course",2],
    ["chance",2],
    ["around",2],
    ["almost",2],
    ["system",2],
    ["single",2],
    ["matter",2],
    ["pretty",2],
    ["police",2],
    ["rather",2],
    ["market",2],
    ["across",2],
    ["likely",2],
    ["couple",2],
    ["window",3],
    ["office",3],
    ["street",3],
    ["doctor",3],
    ["screen",3],
    ["dinner",3],
    ["coffee",3],
    ["minute",3],
    ["second",3],
    ["inside",3],
    ["online",3],
    ["public",3],
    ["common",3],
    ["bright",3],
    ["become",3],
    ["finish",3],
    ["report",3],
    ["record",3],
    ["choice",3],
    ["member",3],
    ["middle",3],
    ["recent",3],
    ["source",3],
    ["things",4],
  ],
  7: [
    ["morning",1],
    ["evening",1],
    ["brother",1],
    ["problem",1],
    ["history",1],
    ["special",1],
    ["already",2],
    ["explain",2],
    ["believe",2],
    ["company",2],
    ["country",2],
    ["message",2],
    ["example",2],
    ["thought",2],
    ["further",2],
    ["instead",2],
    ["perfect",2],
    ["kitchen",3],
    ["station",3],
    ["airport",3],
    ["teacher",3],
    ["student",3],
    ["picture",3],
    ["website",3],
    ["account",3],
    ["clothes",3],
    ["weekend",3],
    ["outside",3],
    ["private",3],
    ["receive",3],
    ["support",3],
    ["control",3],
    ["include",3],
    ["running",3],
    ["success",3],
    ["finally",3],
    ["society",3],
    ["average",3],
    ["certain",3],
    ["medical",3],
    ["exactly",3],
    ["provide",3],
    ["quality",3],
    ["getting",4],
    ["looking",4],
    ["playing",4],
    ["minutes",4],
    ["talking",4],
    ["program",4],
    ["english",4],
    ["decided",4],
    ["changed",4],
    ["waiting",4],
    ["percent",4],
    ["earlier",4],
    ["leaving",4],
    ["winning",4],
    ["calling",4],
    ["defense",4],
    ["numbers",4],
    ["details",4],
    ["telling",4],
    ["effects",4],
    ["greater",4],
    ["driving",4],
    ["holding",4],
    ["showing",4],
    ["putting",4],
    ["sitting",4],
    ["learned",4],
    ["stopped",4],
    ["wearing",4],
  ],
  8: [
    ["question",1],
    ["together",2],
    ["possible",2],
    ["remember",2],
    ["actually",2],
    ["probably",2],
    ["bathroom",3],
    ["language",3],
    ["computer",3],
    ["internet",3],
    ["hospital",3],
    ["national",3],
    ["research",3],
    ["position",3],
    ["response",3],
    ["training",3],
    ["interest",3],
    ["original",3],
    ["evidence",3],
    ["official",3],
    ["services",4],
    ["thinking",4],
    ["received",4],
    ["starting",4],
    ["included",4],
    ["watching",4],
    ["required",4],
    ["designed",4],
    ["favorite",4],
    ["finished",4],
    ["reported",4],
    ["supposed",4],
    ["speaking",4],
    ["becoming",4],
    ["greatest",5],
    ["business",5],
    ["changing",5],
    ["building",5],
    ["breaking",5],
    ["personal",5],
    ["football",6],
    ["practice",6],
    ["activity",6],
    ["bringing",6],
    ["feelings",6],
    ["elements",6],
    ["daughter",6],
    ["drinking",6],
    ["tomorrow",6],
    ["spending",6],
    ["attorney",6],
    ["medicine",6],
    ["mountain",6],
    ["straight",6],
    ["festival",6],
    ["intended",6],
    ["behavior",6],
    ["selected",6],
    ["surprise",6],
    ["magazine",6],
    ["accepted",6],
    ["shopping",6],
    ["terrible",7],
    ["birthday",7],
    ["sentence",7],
    ["combined",7],
    ["pleasure",7],
    ["painting",7],
    ["exercise",7],
    ["affected",7],
    ["recorded",7],
    ["describe",7],
  ],
  9: [
    ["afternoon",1],
    ["sometimes",2],
    ["important",2],
    ["different",2],
    ["beautiful",2],
    ["breakfast",3],
    ["available",3],
    ["education",3],
    ["attention",3],
    ["according",4],
    ["published",4],
    ["announced",4],
    ["described",4],
    ["continued",4],
    ["increased",4],
    ["happening",5],
    ["completed",5],
    ["following",5],
    ["difficult",6],
    ["character",6],
    ["operating",6],
    ["wonderful",6],
    ["excellent",6],
    ["connected",6],
    ["yesterday",6],
    ["interview",6],
    ["expensive",7],
    ["confirmed",7],
    ["supported",7],
    ["committed",7],
    ["listening",7],
    ["chocolate",7],
    ["newspaper",7],
    ["boyfriend",7],
    ["collected",7],
    ["relations",7],
    ["carefully",7],
    ["celebrate",7],
    ["delicious",8],
    ["telephone",8],
    ["destroyed",8],
    ["appointed",8],
    ["introduce",8],
    ["dedicated",8],
    ["scientist",8],
    ["pollution",8],
    ["classroom",8],
    ["reporting",8],
    ["wondering",8],
    ["expressed",8],
    ["protected",8],
    ["recognize",8],
    ["organized",8],
    ["paragraph",8],
    ["returning",8],
    ["vegetable",9],
    ["contained",9],
    ["butterfly",9],
    ["attempted",9],
    ["forgotten",9],
    ["defensive",9],
    ["amendment",9],
    ["ownership",9],
    ["searching",9],
    ["improving",9],
    ["concluded",9],
    ["preferred",9],
    ["screaming",9],
    ["defending",10],
    ["communist",10],
    ["pregnancy",10],
    ["requested",10],
  ],
  10: [
    ["understand",2],
    ["university",2],
    ["experience",2],
    ["especially",3],
    ["production",3],
    ["considered",4],
    ["conditions",4],
    ["operations",5],
    ["connection",6],
    ["discovered",6],
    ["difference",6],
    ["successful",6],
    ["technology",6],
    ["interested",6],
    ["supporting",6],
    ["collection",6],
    ["increasing",7],
    ["girlfriend",7],
    ["everywhere",7],
    ["restaurant",7],
    ["basketball",7],
    ["television",7],
    ["identified",8],
    ["controlled",8],
    ["elementary",8],
    ["understood",8],
    ["performing",8],
    ["suggestion",8],
    ["registered",8],
    ["equivalent",8],
    ["recognized",8],
    ["continuing",9],
    ["dictionary",9],
    ["healthcare",9],
    ["processing",9],
    ["lieutenant",9],
    ["volleyball",9],
    ["subsequent",9],
    ["maintained",9],
    ["publishing",9],
    ["threatened",9],
    ["surrounded",9],
    ["monitoring",9],
    ["struggling",10],
    ["encouraged",10],
    ["collective",10],
    ["protecting",10],
    ["accounting",10],
    ["integrated",10],
    ["classified",10],
    ["conspiracy",10],
    ["mainstream",10],
    ["federation",10],
    ["celebrated",10],
    ["vulnerable",11],
    ["respective",11],
    ["commentary",11],
    ["restricted",11],
    ["collecting",11],
    ["propaganda",11],
    ["underlying",11],
    ["indigenous",11],
    ["applicable",12],
    ["accordance",12],
    ["controller",12],
    ["reportedly",12],
    ["government",12],
    ["authorized",13],
    ["diplomatic",13],
    ["calculated",14],
    ["additional",14],
    ["governance",14],
  ],
  11: [
    ["performance",3],
    ["established",4],
    ["interesting",6],
    ["information",7],
    ["authorities",7],
    ["grandfather",8],
    ["celebration",8],
    ["grandmother",8],
    ["represented",8],
    ["enforcement",9],
    ["supermarket",9],
    ["nationality",9],
    ["distributed",10],
    ["interviewer",10],
    ["accompanied",10],
    ["implemented",11],
    ["transaction",11],
    ["operational",11],
    ["consecutive",11],
    ["proceedings",11],
    ["approaching",11],
    ["controlling",11],
    ["appreciated",11],
    ["statistical",12],
    ["complaining",13],
    ["significant",14],
    ["opportunity",14],
    ["association",15],
    ["competition",15],
    ["appropriate",15],
    ["anticipated",15],
    ["comfortable",15],
    ["traditional",15],
    ["transformed",15],
    ["description",15],
    ["appointment",15],
    ["temperature",16],
    ["anniversary",16],
    ["personality",16],
    ["advertising",16],
    ["specialized",16],
    ["photography",16],
    ["educational",16],
    ["progressive",16],
    ["explanation",16],
    ["inspiration",17],
    ["differently",17],
    ["prosecution",17],
    ["intelligent",17],
    ["communicate",17],
    ["orientation",17],
    ["accommodate",17],
    ["dimensional",17],
    ["questioning",17],
    ["unnecessary",17],
    ["continental",17],
    ["consequence",17],
    ["fascinating",17],
    ["imagination",17],
    ["functioning",18],
    ["convenience",18],
    ["importantly",18],
    ["concentrate",18],
    ["theoretical",18],
    ["distinctive",18],
    ["consistency",18],
    ["recruitment",18],
    ["fortunately",18],
    ["businessman",18],
    ["countryside",18],
    ["determining",19],
    ["frustrating",19],
  ],
} as const);

export const DUEL_TYPING_LENGTHS = Object.freeze(
  Object.keys(WORDS_BY_LENGTH).map(Number).sort((a, b) => a - b),
);

export const DUEL_TYPING_LEXICON: readonly DuelLexiconEntry[] = Object.freeze(
  Object.entries(WORDS_BY_LENGTH).flatMap(([rawLength, rows]) => {
    const length = Number(rawLength);
    return rows.map(([token, sourceLevel], index) =>
      Object.freeze({
        wordId:
          "duel:" +
          String(length) +
          ":" +
          String(index + 1).padStart(3, "0"),
        token,
        length,
        difficultyClass: "core" as const,
        topicTags: Object.freeze(["common"]),
        sourceLevel,
      }),
    );
  }),
);

const ENTRIES_BY_LENGTH = new Map<number, readonly DuelLexiconEntry[]>(
  DUEL_TYPING_LENGTHS.map((length) => [
    length,
    Object.freeze(
      DUEL_TYPING_LEXICON.filter((entry) => entry.length === length),
    ),
  ]),
);

export function duelLexiconEntriesForLength(
  length: number,
): readonly DuelLexiconEntry[] {
  return ENTRIES_BY_LENGTH.get(length) ?? [];
}

export function validateDuelTypingLexicon(
  entries: readonly DuelLexiconEntry[] = DUEL_TYPING_LEXICON,
): string[] {
  const errors: string[] = [];
  const ids = new Set<string>();
  const tokens = new Set<string>();
  const counts = new Map<number, number>();

  for (const entry of entries) {
    if (ids.has(entry.wordId)) {
      errors.push("duplicate wordId: " + entry.wordId);
    }
    ids.add(entry.wordId);
    if (!/^[a-z]+$/.test(entry.token)) {
      errors.push("invalid token: " + entry.token);
    }
    if (entry.token.length !== entry.length) {
      errors.push("length mismatch: " + entry.token);
    }
    if (tokens.has(entry.token)) {
      errors.push("duplicate token: " + entry.token);
    }
    tokens.add(entry.token);
    counts.set(entry.length, (counts.get(entry.length) ?? 0) + 1);
  }

  for (const length of DUEL_TYPING_LENGTHS) {
    if ((counts.get(length) ?? 0) < 64) {
      errors.push(
        "length " + String(length) + " has fewer than 64 entries",
      );
    }
  }
  return errors;
}
