import type { StatBonus } from "../stats/core";
import type { EquipmentPerkId } from "./perks";

export const EQUIPMENT_SLOTS = [
  "weapon",
  "armor",
  "shield",
  "reactor",
  "utility",
  "drone",
  "core",
] as const;

export type EquipmentSlot = (typeof EQUIPMENT_SLOTS)[number];

export const EQUIPMENT_IDS = [
  "pulse-laser-mk1",
  "precision-laser-mk1",
  "ion-cannon-mk1",
  "plated-armor-mk1",
  "adaptive-armor-mk1",
  "kinetic-shell-mk1",
  "deflector-shield-mk1",
  "prism-shield-mk1",
  "capacitor-shield-mk1",
  "compact-reactor-mk1",
  "overclock-reactor-mk1",
  "fusion-reactor-mk1",
  "targeting-module-mk1",
  "salvage-module-mk1",
  "fortune-module-mk1",
  "support-drone-mk1",
  "assault-drone-mk1",
  "ward-drone-mk1",
  "overdrive-core-mk1",
  "salvage-core-mk1",
  "balanced-core-mk1",
  "arc-projector-mk2",
  "rail-driver-mk2",
  "plasma-lance-mk3",
  "ablative-plating-mk2",
  "reactive-armor-mk2",
  "nanoweave-hull-mk3",
  "discharge-shield-mk2",
  "harmonic-shield-mk2",
  "phase-shield-mk3",
  "efficient-reactor-mk2",
  "siphon-reactor-mk2",
  "cryo-reactor-mk3",
  "hunter-killer-pod-mk2",
  "threat-scanner-mk2",
  "overcharge-module-mk3",
  "escort-drone-mk2",
  "interceptor-drone-mk2",
  "wing-drones-mk3",
  "ignition-core-mk2",
  "momentum-core-mk2",
  "quantum-core-mk3",
] as const;

export type EquipmentId = (typeof EQUIPMENT_IDS)[number];

/** Mk.I = plain stats; Mk.II and Mk.III add a perk (see ./perks). */
export type EquipmentTier = 1 | 2 | 3;

export type EquipmentDefinition = {
  id: EquipmentId;
  name: string;
  slot: EquipmentSlot;
  tier: EquipmentTier;
  icon: string;
  description: string;
  stats: StatBonus;
  perk?: EquipmentPerkId;
};

export const EQUIPMENT_REGISTRY: Record<
  EquipmentId,
  EquipmentDefinition
> = {
  "pulse-laser-mk1": {
    id: "pulse-laser-mk1",
    name: "Pulse Laser Mk.I",
    slot: "weapon",
    tier: 1,
    icon: "⌁",
    description: "Balanced starter weapon with steady typing damage.",
    stats: { firepower: 8, focus: 2 },
  },
  "precision-laser-mk1": {
    id: "precision-laser-mk1",
    name: "Precision Laser Mk.I",
    slot: "weapon",
    tier: 1,
    icon: "⌖",
    description: "Lower raw damage, stronger precision and Power gain.",
    stats: { firepower: 4, focus: 7 },
  },
  "ion-cannon-mk1": {
    id: "ion-cannon-mk1",
    name: "Ion Cannon Mk.I",
    slot: "weapon",
    tier: 1,
    icon: "ϟ",
    description: "Heavy typing weapon tuned for raw Firepower with light Reactor support.",
    stats: { firepower: 11, reactor: 1 },
  },
  "plated-armor-mk1": {
    id: "plated-armor-mk1",
    name: "Plated Armor Mk.I",
    slot: "armor",
    tier: 1,
    icon: "▣",
    description: "Starter Hull plating for sustained pressure.",
    stats: { hull: 18, armor: 8 },
  },
  "adaptive-armor-mk1": {
    id: "adaptive-armor-mk1",
    name: "Adaptive Armor Mk.I",
    slot: "armor",
    tier: 1,
    icon: "⬒",
    description: "Balanced Hull, Armor and Hardening package for mixed threats.",
    stats: { hull: 12, armor: 5, ward: 4 },
  },
  "kinetic-shell-mk1": {
    id: "kinetic-shell-mk1",
    name: "Kinetic Shell Mk.I",
    slot: "armor",
    tier: 1,
    icon: "⬛",
    description: "Large Hull reserve with lighter mitigation.",
    stats: { hull: 24, armor: 4 },
  },
  "deflector-shield-mk1": {
    id: "deflector-shield-mk1",
    name: "Deflector Shield Mk.I",
    slot: "shield",
    tier: 1,
    icon: "◈",
    description: "Renewable protection with light Hardening against status effects.",
    stats: { shield: 18, ward: 3 },
  },
  "prism-shield-mk1": {
    id: "prism-shield-mk1",
    name: "Prism Shield Mk.I",
    slot: "shield",
    tier: 1,
    icon: "◇",
    description: "Precision-focused Shield with extra Hardening and Focus.",
    stats: { shield: 12, ward: 4, focus: 4 },
  },
  "capacitor-shield-mk1": {
    id: "capacitor-shield-mk1",
    name: "Capacitor Shield Mk.I",
    slot: "shield",
    tier: 1,
    icon: "⬡",
    description: "Large Shield bank with a small Reactor boost.",
    stats: { shield: 24, reactor: 2 },
  },
  "compact-reactor-mk1": {
    id: "compact-reactor-mk1",
    name: "Compact Reactor Mk.I",
    slot: "reactor",
    tier: 1,
    icon: "⚡",
    description: "Raises Energy capacity and passive regeneration.",
    stats: { energy: 20, reactor: 4 },
  },
  "overclock-reactor-mk1": {
    id: "overclock-reactor-mk1",
    name: "Overclock Reactor Mk.I",
    slot: "reactor",
    tier: 1,
    icon: "↯",
    description: "Faster Reactor output for skill-heavy builds.",
    stats: { energy: 16, reactor: 7 },
  },
  "fusion-reactor-mk1": {
    id: "fusion-reactor-mk1",
    name: "Fusion Reactor Mk.I",
    slot: "reactor",
    tier: 1,
    icon: "◎",
    description: "Large Energy reserve with modest regeneration.",
    stats: { energy: 28, reactor: 2 },
  },
  "targeting-module-mk1": {
    id: "targeting-module-mk1",
    name: "Targeting Module Mk.I",
    slot: "utility",
    tier: 1,
    icon: "⊙",
    description: "Improves precision-oriented combat output.",
    stats: { firepower: 2, focus: 5 },
  },
  "salvage-module-mk1": {
    id: "salvage-module-mk1",
    name: "Salvage Module Mk.I",
    slot: "utility",
    tier: 1,
    icon: "⛭",
    description: "Raises Salvage efficiency with a small Luck bonus.",
    stats: { salvage: 7, luck: 2 },
  },
  "fortune-module-mk1": {
    id: "fortune-module-mk1",
    name: "Fortune Module Mk.I",
    slot: "utility",
    tier: 1,
    icon: "✧",
    description: "Luck-focused utility package with extra Focus.",
    stats: { luck: 7, focus: 2 },
  },
  "support-drone-mk1": {
    id: "support-drone-mk1",
    name: "Support Drone Mk.I",
    slot: "drone",
    tier: 1,
    icon: "◌",
    description: "Small recovery and salvage support package.",
    stats: { reactor: 2, salvage: 4 },
  },
  "assault-drone-mk1": {
    id: "assault-drone-mk1",
    name: "Assault Drone Mk.I",
    slot: "drone",
    tier: 1,
    icon: "◒",
    description: "Offensive drone that supports Firepower and Focus.",
    stats: { firepower: 5, focus: 3 },
  },
  "ward-drone-mk1": {
    id: "ward-drone-mk1",
    name: "ECM Drone Mk.I",
    slot: "drone",
    tier: 1,
    icon: "◐",
    description: "Electronic-countermeasure drone: Hardening and Reactor support.",
    stats: { ward: 5, reactor: 3 },
  },
  "overdrive-core-mk1": {
    id: "overdrive-core-mk1",
    name: "Overdrive Core Mk.I",
    slot: "core",
    tier: 1,
    icon: "✹",
    description: "Power-oriented core with Focus and Energy capacity.",
    stats: { focus: 6, energy: 8 },
  },
  "salvage-core-mk1": {
    id: "salvage-core-mk1",
    name: "Salvage Core Mk.I",
    slot: "core",
    tier: 1,
    icon: "⬢",
    description: "Reward-oriented core combining Salvage and Luck.",
    stats: { salvage: 5, luck: 5 },
  },
  "balanced-core-mk1": {
    id: "balanced-core-mk1",
    name: "Balanced Core Mk.I",
    slot: "core",
    tier: 1,
    icon: "◉",
    description: "General-purpose core with Luck and defensive Hardening.",
    stats: { luck: 4, ward: 3 },
  },
  "arc-projector-mk2": {
    id: "arc-projector-mk2",
    name: "Arc Projector Mk.II",
    slot: "weapon",
    tier: 2,
    icon: "↝",
    description: "Ion lance whose kills spill arc lightning into the next target.",
    stats: { firepower: 12, reactor: 2 },
    perk: "arc-emitter",
  },
  "rail-driver-mk2": {
    id: "rail-driver-mk2",
    name: "Rail Driver Mk.II",
    slot: "weapon",
    tier: 2,
    icon: "⇶",
    description: "Magnetic rail cannon: kill shots punch through into the enemy behind.",
    stats: { firepower: 14, focus: 3 },
    perk: "overpenetration",
  },
  "plasma-lance-mk3": {
    id: "plasma-lance-mk3",
    name: "Plasma Lance Mk.III",
    slot: "weapon",
    tier: 3,
    icon: "✺",
    description: "Superheated plasma lance: perfect kills rupture into a blast wave.",
    stats: { firepower: 18, focus: 6 },
    perk: "plasma-rupture",
  },
  "ablative-plating-mk2": {
    id: "ablative-plating-mk2",
    name: "Ablative Plating Mk.II",
    slot: "armor",
    tier: 2,
    icon: "⛨",
    description: "Sacrificial plates that shrug off the first hit of every stage.",
    stats: { hull: 26, armor: 11 },
    perk: "ablative-plating",
  },
  "reactive-armor-mk2": {
    id: "reactive-armor-mk2",
    name: "Reactive Armor Mk.II",
    slot: "armor",
    tier: 2,
    icon: "⬙",
    description: "Explosive-reactive plates: a hit sets off a pulse that clears nearby shots.",
    stats: { hull: 22, armor: 9, ward: 3 },
    perk: "reactive-armor",
  },
  "nanoweave-hull-mk3": {
    id: "nanoweave-hull-mk3",
    name: "Nanoweave Hull Mk.III",
    slot: "armor",
    tier: 3,
    icon: "⬣",
    description: "Self-knitting hull lattice that repairs itself between hits.",
    stats: { hull: 36, armor: 13 },
    perk: "nanite-weave",
  },
  "discharge-shield-mk2": {
    id: "discharge-shield-mk2",
    name: "Discharge Shield Mk.II",
    slot: "shield",
    tier: 2,
    icon: "⌬",
    description: "Stores the energy of every hit and releases it as an EMP when it collapses.",
    stats: { shield: 26, reactor: 3 },
    perk: "discharge-shield",
  },
  "harmonic-shield-mk2": {
    id: "harmonic-shield-mk2",
    name: "Harmonic Shield Mk.II",
    slot: "shield",
    tier: 2,
    icon: "⏣",
    description: "Tuned to your typing rhythm: perfect words recharge it.",
    stats: { shield: 22, focus: 4 },
    perk: "harmonic-recharge",
  },
  "phase-shield-mk3": {
    id: "phase-shield-mk3",
    name: "Phase Shield Mk.III",
    slot: "shield",
    tier: 3,
    icon: "⌾",
    description: "Shifts the ship out of phase so a hit passes straight through.",
    stats: { shield: 34, ward: 5 },
    perk: "phase-shield",
  },
  "efficient-reactor-mk2": {
    id: "efficient-reactor-mk2",
    name: "Efficient Reactor Mk.II",
    slot: "reactor",
    tier: 2,
    icon: "⊛",
    description: "Low-loss reactor: every skill costs less Energy.",
    stats: { energy: 26, reactor: 6 },
    perk: "efficient-capacitor",
  },
  "siphon-reactor-mk2": {
    id: "siphon-reactor-mk2",
    name: "Siphon Reactor Mk.II",
    slot: "reactor",
    tier: 2,
    icon: "⊚",
    description: "Harvests the wreckage of each kill for Energy.",
    stats: { energy: 22, reactor: 8 },
    perk: "kill-siphon",
  },
  "cryo-reactor-mk3": {
    id: "cryo-reactor-mk3",
    name: "Cryo Reactor Mk.III",
    slot: "reactor",
    tier: 3,
    icon: "❄",
    description: "Supercooled core: skill cooldowns run faster.",
    stats: { energy: 34, reactor: 10 },
    perk: "cryo-coolant",
  },
  "hunter-killer-pod-mk2": {
    id: "hunter-killer-pod-mk2",
    name: "Hunter-Killer Pod Mk.II",
    slot: "utility",
    tier: 2,
    icon: "➹",
    description: "Wing pod that answers a run of kills with micro-missiles.",
    stats: { firepower: 4, focus: 6 },
    perk: "hunter-killer",
  },
  "threat-scanner-mk2": {
    id: "threat-scanner-mk2",
    name: "Threat Scanner Mk.II",
    slot: "utility",
    tier: 2,
    icon: "⌕",
    description: "Tracks incoming fire and jams its guidance: hostile shots fly slower.",
    stats: { focus: 6, ward: 4 },
    perk: "threat-scanner",
  },
  "overcharge-module-mk3": {
    id: "overcharge-module-mk3",
    name: "Overcharge Module Mk.III",
    slot: "utility",
    tier: 3,
    icon: "⍟",
    description: "Feeds surplus reactor output into the Rage capacitor.",
    stats: { focus: 9, luck: 3 },
    perk: "overcharge-module",
  },
  "escort-drone-mk2": {
    id: "escort-drone-mk2",
    name: "Escort Drone Mk.II",
    slot: "drone",
    tier: 2,
    icon: "⟐",
    description: "A drone flies at your wing and snipes letters off the closest enemy.",
    stats: { firepower: 6, focus: 4 },
    perk: "escort-drone",
  },
  "interceptor-drone-mk2": {
    id: "interceptor-drone-mk2",
    name: "Interceptor Drone Mk.II",
    slot: "drone",
    tier: 2,
    icon: "⧫",
    description: "Point-defence drone that shoots down hostile shots.",
    stats: { ward: 6, reactor: 4 },
    perk: "interceptor-drone",
  },
  "wing-drones-mk3": {
    id: "wing-drones-mk3",
    name: "Wing Drones Mk.III",
    slot: "drone",
    tier: 3,
    icon: "❖",
    description: "A pair of escort drones, one on each wing.",
    stats: { firepower: 8, focus: 6, reactor: 3 },
    perk: "wing-drones",
  },
  "ignition-core-mk2": {
    id: "ignition-core-mk2",
    name: "Ignition Core Mk.II",
    slot: "core",
    tier: 2,
    icon: "✵",
    description: "Pre-charged core: every stage starts with Rage in the tank.",
    stats: { focus: 8, energy: 10 },
    perk: "ignition-core",
  },
  "momentum-core-mk2": {
    id: "momentum-core-mk2",
    name: "Momentum Core Mk.II",
    slot: "core",
    tier: 2,
    icon: "⨳",
    description: "Turns a long clean streak into raw damage.",
    stats: { firepower: 5, focus: 7 },
    perk: "momentum-core",
  },
  "quantum-core-mk3": {
    id: "quantum-core-mk3",
    name: "Quantum Core Mk.III",
    slot: "core",
    tier: 3,
    icon: "⎔",
    description: "Quantum-timed core: perfect words shave time off every cooldown.",
    stats: { focus: 10, luck: 5, reactor: 4 },
    perk: "quantum-core",
  },
};

export function isEquipmentId(value: string): value is EquipmentId {
  return Object.hasOwn(EQUIPMENT_REGISTRY, value);
}

export function getEquipmentDefinition(
  id: EquipmentId,
): EquipmentDefinition {
  return EQUIPMENT_REGISTRY[id];
}

export const EQUIPMENT_TIER_LABELS: Record<EquipmentTier, string> = {
  1: "Mk.I",
  2: "Mk.II",
  3: "Mk.III",
};

export function equipmentIdsOfTier(tier: EquipmentTier): EquipmentId[] {
  return EQUIPMENT_IDS.filter((id) => EQUIPMENT_REGISTRY[id].tier === tier);
}
