/** Relaxing (thư giãn) — a lazy lo-fi afternoon under the canopy. */
export default {
  id: "canopy-breeze",
  title: "Canopy Breeze",
  mood: "relaxing",
  key: "F major",
  bpm: 88,
  meter: 4,
  seed: 707,
  progressions: {
    A: ["Fmaj7", "Am7", "Dm7", "Bbmaj7"],
    B: ["Gm7", "C7", "Fmaj7", "Dm7", "Gm7", "C7", "Fmaj7", "Fmaj7"],
    outro: ["Gm7", "C7", "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7"],
  },
  themes: {
    A: [
      [["A4", 1], ["C5", 0.5], ["E5", 1.5], ["C5", 1]],
      [["E5", 1], ["G5", 1], ["E5", 0.5], ["C5", 1.5]],
      [["D5", 1], ["F5", 1], ["A5", 1], ["C6", 1]],
      [["A5", 2], ["F5", 2]],
      [["C5", 0.5], ["D5", 0.5], ["F5", 1], ["A5", 1], ["G5", 1]],
      [["E5", 1.5], ["D5", 0.5], ["C5", 2]],
      [["F5", 1], ["A5", 1], ["D6", 1], ["C6", 1]],
      [["A5", 1], ["F5", 1], ["D5", 2]],
    ],
    B: [
      [["Bb4", 1], ["D5", 1], ["F5", 1], ["D5", 1]],
      [["E5", 1], ["G5", 1], ["Bb5", 1], ["G5", 1]],
      [["A5", 2], ["E5", 1], ["C5", 1]],
      [["F5", 2], ["D5", 2]],
      [["D6", 1], ["Bb5", 1], ["G5", 1], ["F5", 1]],
      [["E5", 1], ["G5", 1], ["C6", 2]],
      [["A5", 3], ["G5", 1]],
      [["F5", 4]],
    ],
  },
  sections: [
    { name: "intro", bars: 4, chords: "A", energy: [0.15, 0.3] },
    { name: "verse", bars: 8, chords: "A", theme: "A", energy: [0.4, 0.55] },
    { name: "chorus", bars: 8, chords: "B", theme: "B", energy: [0.45, 0.62] },
    { name: "verse-2", bars: 8, chords: "A", theme: "A", energy: [0.45, 0.62] },
    { name: "solo", bars: 8, chords: "A", energy: [0.42, 0.58] },
    { name: "chorus-2", bars: 8, chords: "B", theme: "B", energy: [0.5, 0.68] },
    { name: "outro", bars: 6, chords: "outro", energy: [0.2, 0.28], ending: true },
  ],
  palette: {
    pad: { kind: "keys" },
    counter: { kind: "strings", min: [0.9, 0.55], cutoff: 1800 },
    arp: { kind: "musicbox", min: [0.9, 0.52], fast: [2, 2] },
    melody: { kind: ["flute", "flute"], double: { intense: { kind: "keys", octave: 0, gain: 0.4 } } },
    bass: ["walk", "walk"],
    drums: ["lofi", "lofi"],
    swing: 0.18,
    texture: "vinyl",
    room: 0.82,
  },
  loudness: { calm: -16.5, intense: -15 },
  finalNote: "F5",
};
