/** Contemplative (trầm lắng) — Dorian bells ringing through an ice cathedral. */
export default {
  id: "crystal-echoes",
  title: "Crystal Echoes",
  mood: "contemplative",
  key: "F# Dorian",
  bpm: 84,
  meter: 4,
  seed: 606,
  progressions: {
    intro: ["F#m", "B", "F#m", "B"],
    A: ["F#m", "B", "F#m", "B", "D", "A", "E", "E"],
    B: ["D", "E", "C#m", "F#m", "D", "E", "B", "B"],
    drift: ["D", "A", "E", "F#m", "D", "A", "E", "E"],
    outro: ["D", "E", "F#m", "F#m"],
  },
  themes: {
    A: [
      [["C#5", 2], ["A4", 1], ["F#4", 1]],
      [["D#5", 2], ["F#5", 2]],
      [["E5", 1], ["C#5", 1], ["A4", 2]],
      [["B4", 2], ["D#5", 1], ["F#5", 1]],
      [["A5", 2], ["F#5", 1], ["D5", 1]],
      [["E5", 2], ["C#5", 2]],
      [["G#5", 1], ["B5", 1], ["E5", 2]],
      [["B4", 4]],
    ],
    B: [
      [["F#5", 1], ["A5", 1], ["D6", 2]],
      [["B5", 1.5], ["A5", 0.5], ["G#5", 2]],
      [["E5", 1], ["G#5", 1], ["C#6", 2]],
      [["A5", 2], ["F#5", 2]],
      [["D6", 1], ["C#6", 1], ["A5", 2]],
      [["B5", 1], ["G#5", 1], ["E5", 2]],
      [["D#6", 2], ["B5", 1], ["F#5", 1]],
      [["D#5", 4]],
    ],
    // Drifting echoes: a few bell calls answered by the delay.
    E: [[[null, 2], ["A5", 2]], [[null, 4]], [[null, 2], ["G#5", 2]], [[null, 4]]],
  },
  sections: [
    { name: "intro", bars: 4, chords: "intro", energy: [0.1, 0.25] },
    { name: "verse", bars: 8, chords: "A", theme: "A", energy: [0.32, 0.52] },
    { name: "chorus", bars: 8, chords: "B", theme: "B", energy: [0.42, 0.65] },
    { name: "drift", bars: 8, chords: "drift", theme: "E", echo: true, energy: [0.3, 0.48] },
    { name: "verse-2", bars: 8, chords: "A", theme: "A", energy: [0.4, 0.62] },
    { name: "chorus-2", bars: 8, chords: "B", theme: "B", energy: [0.5, 0.72] },
    { name: "outro", bars: 4, chords: "outro", energy: [0.15, 0.22], ending: true },
  ],
  palette: {
    pad: { kind: "supersaw", cutoff: 1100, detune: 10 },
    counter: { kind: "choir", min: [0.5, 0.48], vowel: "oo" },
    arp: { kind: "bell", min: [0.28, 0.25] },
    melody: { kind: ["bell", "keys"], double: { intense: { kind: "bell", octave: 12, gain: 0.25 } } },
    bass: ["sub", "pulse"],
    drums: ["none", "half"],
    texture: "ice",
    room: 0.94,
  },
  glints: ["C#7", "F#6", "A6", "E7"],
  loudness: { calm: -16.8, intense: -15.2 },
  finalNote: "F#5",
};
