/** Fiery (rực lửa) — Phrygian-dominant fire, taiko and an overdriven lead. */
export default {
  id: "ember-rush",
  title: "Ember Rush",
  mood: "fiery",
  key: "E Phrygian dominant",
  bpm: 142,
  meter: 4,
  seed: 303,
  progressions: {
    intro: ["E", "E", "F", "E"],
    A: ["E", "F", "E", "F", "E", "Dm", "F", "E"],
    build: ["Dm", "E", "Dm", "E"],
    B: ["Am", "G", "F", "E", "Am", "G", "F", "E"],
    break: ["E", "F", "E", "F", "E", "F", "E", "E"],
    outro: ["Am", "G", "F", "E", "E", "E"],
  },
  themes: {
    A: [
      [["E5", 0.5], ["F5", 0.5], ["G#5", 1], ["F5", 0.5], ["E5", 0.5], ["B4", 1]],
      [["C5", 0.5], ["D5", 0.5], ["F5", 1], ["E5", 0.5], ["D5", 0.5], ["C5", 1]],
      [["B4", 0.5], ["G#4", 0.5], ["B4", 1], ["E5", 2]],
      [["F5", 1], ["A5", 1], ["G#5", 1], ["F5", 1]],
      [["E5", 0.5], ["F5", 0.5], ["G#5", 0.5], ["A5", 0.5], ["B5", 1], ["A5", 1]],
      [["A5", 1], ["F5", 1], ["D5", 1], ["F5", 1]],
      [["C6", 1.5], ["B5", 0.5], ["A5", 1], ["G#5", 1]],
      [["G#5", 2], ["E5", 2]],
    ],
    B: [
      [["A5", 1], ["C6", 1], ["B5", 0.5], ["A5", 0.5], ["E5", 1]],
      [["G5", 1], ["B5", 1], ["A5", 0.5], ["G5", 0.5], ["D5", 1]],
      [["F5", 1], ["A5", 1], ["G5", 0.5], ["F5", 0.5], ["C5", 1]],
      [["E5", 1], ["G#5", 1], ["B5", 2]],
      [["C6", 1.5], ["B5", 0.5], ["A5", 1], ["E5", 1]],
      [["D6", 1.5], ["C6", 0.5], ["B5", 1], ["G5", 1]],
      [["C6", 1], ["A5", 1], ["F5", 1], ["A5", 1]],
      [["G#5", 1], ["B5", 1], ["E6", 2]],
    ],
  },
  sections: [
    { name: "intro", bars: 4, chords: "intro", energy: [0.18, 0.42] },
    { name: "verse", bars: 8, chords: "A", theme: "A", energy: [0.5, 0.78] },
    { name: "verse-2", bars: 8, chords: "A", theme: "A", energy: [0.55, 0.82] },
    { name: "build", bars: 4, chords: "build", energy: [0.5, 0.78], ramp: [0.1, 0.16], build: true },
    { name: "chorus", bars: 8, chords: "B", theme: "B", energy: [0.7, 0.96] },
    { name: "chorus-2", bars: 8, chords: "B", theme: "B", energy: [0.74, 1] },
    { name: "break", bars: 8, chords: "break", energy: [0.3, 0.5] },
    { name: "verse-3", bars: 8, chords: "A", theme: "A", energy: [0.6, 0.86], build: true },
    { name: "chorus-3", bars: 8, chords: "B", theme: "B", energy: [0.78, 1] },
    { name: "outro", bars: 6, chords: "outro", energy: [0.25, 0.32], ending: true },
  ],
  palette: {
    pad: { kind: "supersaw", cutoff: 1500, detune: 18 },
    counter: { kind: "choir", min: [0.68, 0.7] },
    arp: { kind: "ostinato", min: [0.45, 0.4] },
    melody: { kind: ["brass", "dist"], double: { intense: { kind: "brass", octave: -12, gain: 0.35 } } },
    bass: ["pulse", "drive"],
    drums: ["tribal", "rock"],
    texture: "fire",
    room: 0.8,
  },
  loudness: { calm: -15.6, intense: -14 },
  finalNote: "E4",
};
