/** Triumphant (hùng tráng) — the final gate: choir, brass and taiko. */
export default {
  id: "eternity-gate",
  title: "Eternity Gate",
  mood: "triumphant",
  key: "C minor / Eb major",
  bpm: 134,
  meter: 4,
  seed: 1313,
  progressions: {
    intro: ["Cm", "Cm", "Ab", "G"],
    A: ["Cm", "Ab", "Eb", "Bb", "Cm", "Ab", "Fm", "G"],
    B: ["Ab", "Bb", "Eb", "Cm", "Ab", "Bb", "Eb", "Eb"],
    outro: ["Ab", "Bb", "Eb", "Eb", "Eb", "Eb"],
  },
  themes: {
    A: [
      [["C5", 1], ["G5", 1], ["Eb5", 1], ["G5", 1]],
      [["Ab5", 1.5], ["G5", 0.5], ["Eb5", 2]],
      [["Bb5", 1], ["G5", 1], ["Eb5", 1], ["G5", 1]],
      [["F5", 2], ["D5", 2]],
      [["Eb5", 1], ["G5", 1], ["C6", 1], ["D6", 1]],
      [["Eb6", 1.5], ["D6", 0.5], ["C6", 2]],
      [["Ab5", 1], ["C6", 1], ["F6", 1], ["Eb6", 1]],
      [["D6", 2], ["B5", 2]],
    ],
    B: [
      [["C6", 2], ["Eb6", 2]],
      [["D6", 1.5], ["C6", 0.5], ["Bb5", 2]],
      [["G5", 1], ["Bb5", 1], ["Eb6", 2]],
      [["Eb6", 1], ["D6", 1], ["C6", 1], ["G5", 1]],
      [["Ab5", 1], ["C6", 1], ["Eb6", 1], ["F6", 1]],
      [["F6", 1.5], ["Eb6", 0.5], ["D6", 1], ["Bb5", 1]],
      [["Eb6", 2], ["G6", 2]],
      [["Eb6", 4]],
    ],
  },
  sections: [
    { name: "intro", bars: 4, chords: "intro", energy: [0.25, 0.5] },
    { name: "verse", bars: 8, chords: "A", theme: "A", energy: [0.6, 0.84] },
    { name: "verse-2", bars: 8, chords: "A", theme: "A", energy: [0.62, 0.86], build: true },
    { name: "chorus", bars: 8, chords: "B", theme: "B", energy: [0.75, 0.98] },
    { name: "break", bars: 8, chords: "A", energy: [0.35, 0.6] },
    { name: "verse-3", bars: 8, chords: "A", theme: "A", energy: [0.65, 0.9], build: true },
    { name: "chorus-2", bars: 8, chords: "B", theme: "B", energy: [0.85, 1] },
    { name: "chorus-3", bars: 8, chords: "B", theme: "B", energy: [0.88, 1] },
    { name: "outro", bars: 6, chords: "outro", energy: [0.3, 0.4], ending: true },
  ],
  palette: {
    pad: { kind: "strings", cutoff: 2600 },
    counter: { kind: "choir", min: [0.6, 0.6] },
    arp: { kind: "ostinato", min: [0.5, 0.45] },
    melody: { kind: ["brass", "brass"], double: { intense: { kind: "lead", octave: -12, gain: 0.35 } } },
    bass: ["pulse", "drive"],
    drums: ["epic", "epic"],
    texture: "air",
    room: 0.86,
  },
  loudness: { calm: -15.4, intense: -13.8 },
  finalNote: "Eb5",
};
