/** Gloomy (u ám) — drones, low choir and a heartbeat in the shadow woods. */
export default {
  id: "hollow-roots",
  title: "Hollow Roots",
  mood: "gloomy",
  key: "D minor",
  bpm: 68,
  meter: 4,
  seed: 909,
  progressions: {
    intro: ["Dm", "Eb", "Dm", "Dm"],
    A: ["Dm", "Eb", "Dm", "Dm", "Bb", "Gm", "A", "A"],
    B: ["Gm", "Eb", "Bb", "A", "Gm", "Eb", "A", "A"],
    depth: ["Dm", "Eb", "Dm", "Eb"],
    outro: ["Gm", "A", "Dm", "Dm"],
  },
  themes: {
    A: [
      [["D5", 2], ["F5", 1], ["E5", 1]],
      [["Eb5", 3], ["D5", 1]],
      [["A4", 2], ["D5", 2]],
      [["F5", 1], ["E5", 1], ["D5", 1], ["C#5", 1]],
      [["D5", 2], ["F5", 2]],
      [["Bb4", 2], ["G4", 2]],
      [["A4", 1], ["C#5", 1], ["E5", 2]],
      [["A4", 4]],
    ],
    B: [
      [["G5", 2], ["Bb5", 1], ["A5", 1]],
      [["G5", 2], ["Eb5", 2]],
      [["F5", 2], ["D5", 1], ["Bb4", 1]],
      [["E5", 2], ["C#5", 2]],
      [["D6", 2], ["Bb5", 2]],
      [["C6", 1], ["Bb5", 1], ["G5", 2]],
      [["A5", 2], ["E5", 2]],
      [["A4", 4]],
    ],
  },
  sections: [
    { name: "intro", bars: 4, chords: "intro", energy: [0.08, 0.25] },
    { name: "verse", bars: 8, chords: "A", theme: "A", energy: [0.3, 0.52] },
    { name: "chorus", bars: 8, chords: "B", theme: "B", energy: [0.4, 0.65] },
    { name: "depth", bars: 4, chords: "depth", heartbeat: true, energy: [0.2, 0.4] },
    { name: "verse-2", bars: 8, chords: "A", theme: "A", energy: [0.38, 0.6] },
    { name: "chorus-2", bars: 8, chords: "B", theme: "B", energy: [0.45, 0.7] },
    { name: "outro", bars: 4, chords: "outro", energy: [0.12, 0.2], ending: true },
  ],
  palette: {
    pad: { kind: "supersaw", cutoff: 700, detune: 10 },
    counter: { kind: "choir", min: [0.35, 0.35], low: 50, high: 69 },
    arp: { kind: "bell", min: [0.45, 0.4] },
    melody: { kind: ["flute", "strings"], octave: -12 },
    bass: ["drone", "drone"],
    drums: ["heartbeat", "requiem"],
    texture: "deep",
    room: 0.92,
  },
  loudness: { calm: -16.8, intense: -15.2 },
  finalNote: "D4",
};
