/** Blazing climax (bốc cháy) — taiko, choir and brass over a C-minor march. */
export default {
  id: "molten-crown",
  title: "Molten Crown",
  mood: "blazing",
  key: "C minor",
  bpm: 126,
  meter: 4,
  seed: 404,
  progressions: {
    intro: ["Cm", "Cm", "Ab", "Bb"],
    A: ["Cm", "Ab", "Eb", "Bb"],
    B: ["Fm", "Ab", "Bb", "Cm", "Ab", "Bb", "G", "G"],
    break: ["Ab", "Bb", "Cm", "Cm", "Ab", "Bb", "G", "G"],
    outro: ["Ab", "Bb", "Cm", "Cm", "Cm", "Cm"],
  },
  themes: {
    A: [
      [["G4", 1], ["C5", 1], ["Eb5", 1], ["D5", 1]],
      [["C5", 1.5], ["Bb4", 0.5], ["Ab4", 2]],
      [["Bb4", 1], ["Eb5", 1], ["G5", 1], ["F5", 1]],
      [["D5", 2], ["F5", 1], ["D5", 1]],
      [["Eb5", 1], ["G5", 1], ["C6", 1.5], ["Bb5", 0.5]],
      [["Ab5", 1], ["G5", 1], ["Eb5", 1], ["C5", 1]],
      [["G5", 1.5], ["F5", 0.5], ["Eb5", 1], ["D5", 1]],
      [["F5", 2], ["D5", 2]],
    ],
    B: [
      [["C6", 2], ["Ab5", 1], ["F5", 1]],
      [["Eb6", 2], ["C6", 1], ["Ab5", 1]],
      [["D6", 1.5], ["C6", 0.5], ["Bb5", 1], ["F5", 1]],
      [["G5", 2], ["C6", 2]],
      [["C6", 1], ["Eb6", 1], ["D6", 1], ["C6", 1]],
      [["Bb5", 1], ["D6", 1], ["F6", 1], ["D6", 1]],
      [["B5", 2], ["D6", 1], ["B5", 1]],
      [["G5", 4]],
    ],
  },
  sections: [
    { name: "intro", bars: 4, chords: "intro", energy: [0.15, 0.4] },
    { name: "verse", bars: 8, chords: "A", theme: "A", energy: [0.5, 0.75] },
    { name: "verse-2", bars: 8, chords: "A", theme: "A", energy: [0.54, 0.8], build: true },
    { name: "chorus", bars: 8, chords: "B", theme: "B", energy: [0.72, 0.95] },
    { name: "break", bars: 8, chords: "break", energy: [0.3, 0.55] },
    { name: "verse-3", bars: 8, chords: "A", theme: "A", energy: [0.6, 0.85], build: true },
    { name: "chorus-2", bars: 8, chords: "B", theme: "B", energy: [0.8, 1] },
    { name: "chorus-3", bars: 8, chords: "B", theme: "B", energy: [0.82, 1] },
    { name: "outro", bars: 6, chords: "outro", energy: [0.25, 0.35], ending: true },
  ],
  palette: {
    pad: { kind: "strings", cutoff: 2200 },
    counter: { kind: "choir", min: [0.6, 0.6] },
    arp: { kind: "ostinato", min: [1.1, 0.72] },
    melody: { kind: ["brass", "brass"], double: { intense: { kind: "lead", octave: 0, gain: 0.4 } } },
    bass: ["sub", "drive"],
    drums: ["epic", "epic"],
    texture: "fire",
    room: 0.84,
  },
  loudness: { calm: -15.6, intense: -14 },
  finalNote: "C5",
};
