/** Gentle (nhẹ nhàng) — a music-box waltz under the stars. */
export default {
  id: "starlit-lullaby",
  title: "Starlit Lullaby",
  mood: "gentle",
  key: "D major",
  bpm: 84,
  meter: 3,
  seed: 202,
  progressions: {
    intro: ["D", "A/C#", "Bm", "F#m"],
    verse: ["D", "A/C#", "Bm", "F#m", "G", "D/F#", "Em", "A"],
    chorus: ["G", "A", "F#m", "Bm", "G", "A", "D", "D"],
    bridge: ["Em", "F#m", "G", "A", "Em", "F#m", "G", "A"],
    outro: ["G", "A", "D", "D", "D", "D"],
  },
  themes: {
    A: [
      [["A5", 2], ["F#5", 1]],
      [["E5", 2], ["C#5", 1]],
      [["D5", 1], ["F#5", 1], ["B5", 1]],
      [["A5", 2], ["F#5", 1]],
      [["G5", 1], ["B5", 1], ["D6", 1]],
      [["A5", 2], ["F#5", 1]],
      [["G5", 1], ["E5", 1], ["B4", 1]],
      [["C#5", 2], ["E5", 1]],
    ],
    B: [
      [["B5", 1.5], ["A5", 0.5], ["G5", 1]],
      [["A5", 1.5], ["G5", 0.5], ["E5", 1]],
      [["F#5", 2], ["C#5", 1]],
      [["D5", 1], ["F#5", 1], ["B5", 1]],
      [["D6", 2], ["B5", 1]],
      [["C#6", 1.5], ["B5", 0.5], ["A5", 1]],
      [["F#5", 3]],
      [["D5", 3]],
    ],
  },
  sections: [
    { name: "intro", bars: 4, chords: "intro", energy: [0.1, 0.2] },
    { name: "verse", bars: 8, chords: "verse", theme: "A", energy: [0.35, 0.52] },
    { name: "verse-2", bars: 8, chords: "verse", theme: "A", energy: [0.4, 0.58] },
    { name: "chorus", bars: 8, chords: "chorus", theme: "B", energy: [0.5, 0.7] },
    { name: "bridge", bars: 8, chords: "bridge", energy: [0.38, 0.52], ramp: [0.1, 0.16], build: true },
    { name: "verse-3", bars: 8, chords: "verse", theme: "A", energy: [0.45, 0.66] },
    { name: "chorus-2", bars: 8, chords: "chorus", theme: "B", energy: [0.55, 0.78] },
    { name: "outro", bars: 6, chords: "outro", energy: [0.15, 0.22], ending: true },
  ],
  palette: {
    pad: { kind: "glass", cutoff: 1300 },
    counter: { kind: "strings", min: [0.5, 0.45], low: 62, high: 81, cutoff: 2400 },
    arp: { kind: "musicbox", min: [0.3, 0.25], fast: [2, 2] },
    melody: { kind: ["musicbox", "flute"], double: { intense: { kind: "musicbox", octave: 12, gain: 0.3 } } },
    bass: ["sub", "pulse"],
    drums: ["none", "waltz"],
    texture: "air",
    room: 0.9,
  },
  loudness: { calm: -17, intense: -15.5 },
  finalNote: "D6",
};
